# Generated by Django 4.1.2 on 2024-07-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id_nav', models.AutoField(db_column='idNav', primary_key=True, serialize=False)),
                ('nombre_nav', models.CharField(max_length=20)),
                ('enlace_nav', models.CharField(max_length=300)),
            ],
        ),
    ]
